### ISSUE TITLE
input array's first element is zero-ed out..

### ISSUE THREAD

**Issue by toravir** [PacktPublishing/Java-Coding-Problems#8]
Is this expected ??

https://github.com/PacktPublishing/Java-Coding-Problems/blob/d89310b7389aba87c019a32d861ad2738cea2df7/Chapter05/P127_FenwickTree/src/modern/challenge/FenwickTree.java#L21

**Comment by AnghelLeonard** [comment]
@toravir thank you for the comment.
The Fenwick Tree algorithm relies on a 1-index based array. The first element should be 0. Of course, this doesn't mean that you cannot find workarounds to avoid that line. Please, consider further explanation in the book.
